version: '3'
services:
    cameracalibration:
        build: notebook
        image: camera_calibration:1
        container_name: camera-calibration
        ports:
            - '8892:8888'
        volumes:
            - "../notebooks:/home/jovyan/notebooks"
        # tty: true
        # stdin_open : true
        # env_file: my_env.txt
        environment: 
            GRANT_SUDO: "yes"
            PYTHONPATH: "/home/jovyan/notebooks/my_modules"
        command: 
            "start-notebook.sh --NotebookApp.password=${NotebookApp_password}"
