version: '3'
services:
    cameracalibration:
        build: notebook
        image: camera_calibration:1
        container_name: camera-calibration
        ports:
            - '8892:8888'
        volumes:
            - "../works:/home/jovyan/works"
        # tty: true
        # stdin_open : true
        
        # environment: 
        #     GRANT_SUDO: "yes"
        # command: 
        #     start-notebook.sh
